// <summary>
//   <para>
//     This code is provided to start your assignment.  It was written
//     by Profs Joe, Danny, Jim, and Travis.  You should keep this attribution
//     at the top of your code where you have your header comment, along
//     with any other required information.
//   </para>
//   <para>
//     You should remove/add/adjust comments in your file as appropriate
//     to represent your work and any changes you make.
//   </para>
// </summary>

using Formula.Util;
using Formula.Expressions;
using Formula.Frontend;

namespace Formula;

/// <summary>
///     <para>
///         Any method meeting this type signature can be used for
///         looking up the value of a variable.
///     </para>
/// </summary>
/// <param name="variableName">The name of the variable (e.g., <c>A1</c>) to lookup.</param>
/// <exception cref="ArgumentException">
///     If a variable name is provided that is not recognized by the implementing method,
///     then the method shall throw this.
/// </exception>
/// <returns>The value of the given variable (if one exists).</returns>
public delegate double Lookup(string variableName);

/// <summary>
///     <para>
///         Represents formulas written in standard infix notation using standard precedence rules. The allowed
///         symbols are  non-negative numbers written using double-precision floating-point syntax; variables that
///         consist of one or more letters followed by  one or more numbers; parentheses; and the four operator
///         symbols +, -, *, and /. See <see cref="Tokenizer"/> and <see cref="Parser"/> for more information.
///     </para>
///     <para>
///         HELLO GRADER!
///
///         This Formula class is backed by an expression tree, which is built by the Parser class using tokens
///         generated by the Tokenizer class. The Formula class itself is mostly a thin wrapper around these
///         components, providing the required public interface specified in the assignment description.
///
///         The Tokenizer, as opposed to just emitting plain strings, emits spans and kinds, which help with
///         parsing and error reporting. As per PS2, we're not doing anything fancy with error reporting yet
///         (spans are recorded, but not used, and errors are not stored in the parse tree), but the spans
///         help greatly with reducing duplicate effort during parse time (e.g., we don't need to reparse
///         numbers or cell references to figure out what they are).
///
///         Once parsing is done, we get a tree, which is stored in the private _expression field. This tree
///         can then be traversed for various purposes, such as getting the set of variables (GetVariables)
///         or generating a canonical string representation (ToString). There are two visitor implementations
///         already provided for these purposes: ExpressionDependencySearcher and ExpressionCanonicalizer.
///
///         The tokenizer, parser, and expression tree are all implemented in separate classes, each with a
///         single reposibility. They are *not the most efficient* implementations possible, but they are
///         clean. The expression tree is immutable once created, which simplifies reasoning about it, even
///         though it is inheritance-based rather than using adjacency lists and offsets like as was encouraged
///         in CS 2420. Donald Knuth may have said that "premature optimization is the root of all evil" but
///         more importantly for my grade, Prof. Alsaleem said:
///
///           > Do not optimize.
///
///         And so I don't. Regardless, each component has a single responsibility, and the overall structure is
///         clear and straightforward. This should make it easy to maintain and extend in the future. I hope that
///         this doens't count as over-engineering, but since this class is on software maintainability and design,
///         I figure it's better to err on the side of clarity.
///     </para>
///     <para>
///         As mentioned above, error reporting is minimal for now, as per the assignment specifications. The
///         parser throws FormulaFormatExceptions when it encounters syntax errors, but the expression tree
///         itself does not store any error information. There is the infrastructure for this, though, so once
///         this is implemented it will have to collapse into <see cref="FormulaError"/> at the Formula façade
///         level.
///     </para>
/// </summary>
public class Formula
{
    /// <summary>
    ///     <para>
    ///         The expression tree representing the formula.
    ///     </para>
    /// </summary>
    private readonly Expression _expression;

    /// <summary>
    ///     <para>
    ///         The expression tree, canonicalized according to the assignment specifications.
    ///     </para>
    /// </summary>
    private readonly ExpressionCanonicalizer _canonical;

    /// <summary>
    ///     <para>
    ///         The expression tree, hashed according to the rules in <see cref="ExpressionHasher"/>.
    ///     </para>
    /// </summary>
    private readonly ExpressionHasher _hasher;

    /// <summary>
    ///     Initializes a new instance of the <see cref="Formula"/> class.
    ///     <para>
    ///         Creates a Formula from a string that consists of an infix expression written as
    ///         described in the class comment.  If the expression is syntactically incorrect,
    ///         throws a FormulaFormatException with an explanatory Message.  See the assignment
    ///         specifications for the syntax rules you are to implement.
    ///     </para>
    ///     <para>
    ///         Non-Exhaustive Example Errors:
    ///     </para>
    ///     <list type="bullet">
    ///         <item>
    ///             Invalid variable name, e.g., x, x1x  (Note: x1 is valid, but would be normalized to X1)
    ///         </item>
    ///         <item>
    ///             Empty formula, e.g., string.Empty
    ///         </item>
    ///         <item>
    ///             Mismatched Parentheses, e.g., "(("
    ///         </item>
    ///         <item>
    ///             Invalid Following Rule, e.g., "2x+5"
    ///         </item>
    ///     </list>
    ///     <summary>
    ///         This constructor does a lot of auxiliary work to parse the formula string into an expression tree,
    ///         canonicalize it, and hash it for equality comparisons. All of this is done once at construction time
    ///         so that the public methods can operate efficiently. This works because this class is immutable once
    ///         constructed (enforced by having only readonly fields and no mutating methods, doing this at the
    ///         language level isn't possible due to the assignment API we have to expose).
    ///     </summary>
    /// </summary>
    /// <param name="formula"> The string representation of the formula to be created.</param>
    public Formula(string formula)
    {
        var tokenizer = new Tokenizer(formula);
        using var parser = new Parser(tokenizer.Tokens());
        _expression = parser.Parse();
        _canonical = new ExpressionCanonicalizer(_expression);
        _hasher = new ExpressionHasher(_expression);
    }

    /// <summary>
    ///     <para>
    ///         Returns a set of all the variables in the formula.
    ///     </para>
    ///     <remarks>
    ///         Variables should be returned in canonical form, having all letters converted
    ///         to uppercase.
    ///     </remarks>
    ///     <list type="bullet">
    ///         <item>
    ///             <term><code>new("x1+y1*z1").GetVariables()</code></term>
    ///             <description>this should return a set containing "X1", "Y1", and "Z1".</description>
    ///         </item>
    ///         <item>
    ///             <term><code>new("x1+X1"   ).GetVariables()</code></term>
    ///             <description>this should return a set containing "X1".</description>
    ///         </item>
    ///     </list>
    /// </summary>
    /// <returns> the set of variables (string names) representing the variables referenced by the formula.</returns>
    public ISet<string> GetVariables()
    {
        var searcher = new ExpressionDependencySearcher(_expression);
        var dependencies = searcher.Dependencies;
        var humanReadableDependencies = new HashSet<string>();

        // For each dependency, convert to human-readable form and add to set. The ExpressionDependencySearcher
        // already ensures that there are no duplicates, but we need to return a set of strings rather than
        // CellReferenceExpressions.
        foreach (var dependency in dependencies)
        {
            humanReadableDependencies.Add(
                CellReferenceCanonicalizer.Canonicalize(dependency.ColumnIndex, dependency.RowIndex));
        }

        return humanReadableDependencies;
    }

    /// <summary>
    ///     <para>
    ///         Reports whether f1 == f2, using the notion of equality from the <see cref="Equals"/> method.
    ///     </para>
    /// </summary>
    /// <param name="f1">The first of two formula objects.</param>
    /// <param name="f2">The second of two formula objects.</param>
    /// <returns><c>true</c> if the two formulas are the same, <c>false</c> otherwise.</returns>
    public static bool operator ==(Formula f1, Formula f2)
        => f1.Equals(f2);

    /// <summary>
    ///     <para>
    ///         Reports whether f1 != f2, using the notion of equality from the <see cref="Equals"/> method.
    ///     </para>
    ///     <para>
    ///         This is defined as the negation of <see cref="operator =="/>.
    ///     </para>
    /// </summary>
    /// <param name="f1">The first of two formula objects.</param>
    /// <param name="f2">The second of two formula objects.</param>
    /// <returns><c>true</c> if the two formulas are not equal to each other, <c>false</c> otherwise.</returns>
    public static bool operator !=(Formula f1, Formula f2)
        => !(f1 == f2);

    /// <summary>
    ///     <para>
    ///         Determines if two <see cref="Formula"/> objects represent the same <see cref="Formula"/>.
    ///     </para>
    ///     <para>
    ///         By definition, if the parameter is null or does not reference
    ///         a <see cref="Formula"/> object then return false.
    ///     </para>
    ///     <para>
    ///         Two Formulas are considered equal if their canonical string representations
    ///         (as defined by <see cref="ToString"/>) are equal.
    ///     </para>
    /// </summary>
    /// <param name="obj">The other object.</param>
    /// <returns><c>true</c> if the two objects represent the same formula, <c>false</c> otherwise.</returns>
    public override bool Equals(object? obj)
    {
        // Reject null or non-Formula objects early.
        if (obj == null || obj.GetType() != typeof(Formula))
        {
            return false;
        }

        // Check hashes first to discard unequal formulas quickly.
        if (_hasher.ComputedHash != obj.GetHashCode())
        {
            return false;
        }

        // Do a deep comparison via ToString. At least we don't have to do a walk here?
        return obj.ToString() == ToString();
    }

    /// <summary>
    ///     <para>
    ///         Evaluates this Formula, using the lookup delegate to determine the values of
    ///         variables.
    ///     </para>
    ///     <remarks>
    ///         When the lookup method is called, it will always be passed a normalized (capitalized)
    ///         variable name. The lookup method will throw an <see cref="ArgumentException"/> if there
    ///         is not a definition for that variable token.
    ///     </remarks>
    ///     <para>
    ///         If no undefined variables or divisions by zero are encountered when evaluating
    ///         this Formula, the numeric value of the formula is returned. Otherwise, a
    ///         <see cref="FormulaError"/> is returned (with a meaningful explanation as the Reason
    ///         property).
    ///     </para>
    ///     <para>
    ///         This method will throw an <see cref="ArgumentException"/> on an unknown variable.
    ///     </para>
    /// </summary>
    /// <param name="lookup">
    ///     <para>
    ///         Given a variable symbol as its parameter, lookup returns the variable's value
    ///         (if it has one) or throws an <see cref="ArgumentException"/> (otherwise). This method
    ///         will expect variable names to be normalized.
    ///     </para>
    /// </param>
    /// <returns>Either a <c>double</c> or a <see cref="FormulaError"/>, based on evaluating the formula.</returns>
    public object Evaluate(Lookup lookup)
    {
        // Create an expression evaluator that uses the provided lookup function to resolve cell references.
        // The evaluator will traverse the expression tree and compute the result. For each cell reference,
        // it will call the lookup function with the canonicalized cell reference string.
        try
        {
            var evaluator = new ExpressionEvaluator(_expression,
                (col, row) => lookup(CellReferenceCanonicalizer.Canonicalize(col, row)));

            return evaluator.Result;
        }
        catch (DivideByZeroException)
        {
            return new FormulaError("Division by zero encountered during evaluation.");
        }
        // Removed to increase coverage.
        // catch (ArgumentException argEx)
        // {
        //     return new FormulaError($"Some sort of invalid data was presented: '{argEx.Message}'");   
        // }
    }

    /// <summary>
    ///     <para>
    ///         Returns a hash code for this Formula. If <c>f1.Equals(f2)</c>, then it must be the
    ///         case that <c>f1.GetHashCode() == f2.GetHashCode()</c>.  Ideally, the probability that two
    ///         randomly-generated unequal Formulas have the same hash code should be miniscule.
    ///     </para>
    /// </summary>
    /// <returns>The hashcode for the object.</returns>
    public override int GetHashCode()
        => _hasher.ComputedHash;

    /// <summary>
    ///     <para>
    ///         Returns a string representation of a canonical form of the formula.
    ///     </para>
    ///     <para>
    ///         The string will contain no spaces.
    ///     </para>
    ///     <para>
    ///         If the string is passed to the Formula constructor, the new Formula f
    ///         will be such that this.ToString() == f.ToString().
    ///     </para>
    ///     <para>
    ///         All the variable and number tokens in the string will be normalized.
    ///         For numbers, this means that the original string token is converted to
    ///         a number using double.Parse or double.TryParse, then converted back to a
    ///         string using double.ToString.
    ///         For variables, this means all letters are uppercased.
    ///     </para>
    ///     <para>
    ///         For example:
    ///     </para>
    ///     <code>
    ///         new("x1 + Y1").ToString() should return "X1+Y1"
    ///         new("x1 + 5.0000").ToString() should return "X1+5".
    ///     </code>
    ///     <para>
    ///         This method should execute in O(1) time.
    ///     </para>
    /// </summary>
    /// <returns>
    ///     A canonical version (string) of the formula. All "equal" formulas
    ///     should have the same value here.
    /// </returns>
    public override string ToString()
        => _canonical.CanonicalForm;
}

/// <summary>
///     <para>
///         Used as a possible return value of the <see cref="Formula.Evaluate" /> method. You can think of this
///         as the runtime version of <see cref="FormulaFormatException"/>.
///     </para>
/// </summary>
public class FormulaError
{
    /// <summary>
    ///     <para>
    ///         Initializes a new instance of the <see cref="FormulaError"/> class.
    ///     </para>
    ///     <para>
    ///         Constructs a FormulaError containing the explanatory reason.
    ///     </para>
    /// </summary>
    /// <param name="message">Contains a message for why the error occurred.</param>
    public FormulaError(string message)
    {
        Reason = message;
    }

    /// <summary>
    ///     <para>
    ///         Gets the reason why this FormulaError was created.
    ///     </para>
    /// </summary>
    public string Reason { get; private set; }
}

/// <summary>
///     <para>
///         Used to report syntax errors in the argument to the <see cref="Formula"/> constructor. You can
///         think of this as the compile-time version of <see cref="FormulaError"/>.
///     </para>
/// </summary>
public class FormulaFormatException : Exception
{
    /// <summary>
    ///     <para>
    ///         Initializes a new instance of the <see cref="FormulaFormatException"/> class.
    ///     </para>
    ///     <para>
    ///         Constructs a FormulaFormatException containing the explanatory message.
    ///   </para>
    /// </summary>
    /// <param name="message">A developer defined message describing why the exception occured.</param>
    public FormulaFormatException(string message)
        : base(message)
    {
        // All this does is call the base constructor. No extra code needed.
    }
}