// <summary>
//   <para>
//     This code is provided to start your assignment.  It was written
//     by Profs Joe, Danny, Jim, and Travis.  You should keep this attribution
//     at the top of your code where you have your header comment, along
//     with any other required information.
//   </para>
//   <para>
//     You should remove/add/adjust comments in your file as appropriate
//     to represent your work and any changes you make.
//   </para>
// </summary>

using Formula.Util;
using Formula.Expressions;
using Formula.Frontend;

namespace Formula;

/// <summary>
///     <para>
///         Represents formulas written in standard infix notation using standard precedence rules. The allowed
///         symbols are  non-negative numbers written using double-precision floating-point syntax; variables that
///         consist of one or more letters followed by  one or more numbers; parentheses; and the four operator
///         symbols +, -, *, and /. See <see cref="Tokenizer"/> and <see cref="Parser"/> for more information.
///     </para>
///     <para>
///         HELLO GRADER!
///
///         This Formula class is backed by an expression tree, which is built by the Parser class using tokens
///         generated by the Tokenizer class. The Formula class itself is mostly a thin wrapper around these
///         components, providing the required public interface specified in the assignment description.
///
///         The Tokenizer, as opposed to just emitting plain strings, emits spans and kinds, which help with
///         parsing and error reporting. As per PS2, we're not doing anything fancy with error reporting yet
///         (spans are recorded, but not used, and errors are not stored in the parse tree), but the spans
///         help greatly with reducing duplicate effort during parse time (e.g., we don't need to reparse
///         numbers or cell references to figure out what they are).
///
///         Once parsing is done, we get a tree, which is stored in the private _expression field. This tree
///         can then be traversed for various purposes, such as getting the set of variables (GetVariables)
///         or generating a canonical string representation (ToString). There are two visitor implementations
///         already provided for these purposes: ExpressionDependencySearcher and ExpressionCanonicalizer.
///
///         The tokenizer, parser, and expression tree are all implemented in separate classes, each with a
///         single reposibility. They are *not the most efficient* implementations possible, but they are
///         clean. The expression tree is immutable once created, which simplifies reasoning about it, even
///         though it is inheritance-based rather than using adjacency lists and offsets like as was encouraged
///         in CS 2420. Donald Knuth may have said that "premature optimization is the root of all evil" but
///         more importantly for my grade, Prof. Alsaleem said:
///
///           > Do not optimize.
///
///         And so I don't. Regardless, each component has a single responsibility, and the overall structure is
///         clear and straightforward. This should make it easy to maintain and extend in the future. I hope that
///         this doens't count as over-engineering, but since this class is on software maintainability and design,
///         I figure it's better to err on the side of clarity.
///     </para>
/// </summary>
public class Formula
{
    /// <summary>
    ///     <para>
    ///         The expression tree representing the formula.
    ///     </para>
    /// </summary>
    private readonly Expression _expression;

    /// <summary>
    ///     Initializes a new instance of the <see cref="Formula"/> class.
    ///     <para>
    ///         Creates a Formula from a string that consists of an infix expression written as
    ///         described in the class comment.  If the expression is syntactically incorrect,
    ///         throws a FormulaFormatException with an explanatory Message.  See the assignment
    ///         specifications for the syntax rules you are to implement.
    ///     </para>
    ///     <para>
    ///         Non-Exhaustive Example Errors:
    ///     </para>
    ///     <list type="bullet">
    ///         <item>
    ///             Invalid variable name, e.g., x, x1x  (Note: x1 is valid, but would be normalized to X1)
    ///         </item>
    ///         <item>
    ///             Empty formula, e.g., string.Empty
    ///         </item>
    ///         <item>
    ///             Mismatched Parentheses, e.g., "(("
    ///         </item>
    ///         <item>
    ///             Invalid Following Rule, e.g., "2x+5"
    ///         </item>
    ///   </list>
    /// </summary>
    /// <param name="formula"> The string representation of the formula to be created.</param>
    public Formula(string formula)
    {
        var tokenizer = new Tokenizer(formula);
        using var parser = new Parser(tokenizer.Tokens());
        _expression = parser.Parse();
    }

    /// <summary>
    ///     <para>
    ///         Returns a set of all the variables in the formula.
    ///     </para>
    ///     <remarks>
    ///         Variables should be returned in canonical form, having all letters converted
    ///         to uppercase.
    ///     </remarks>
    ///     <list type="bullet">
    ///         <item>
    ///             <term><code>new("x1+y1*z1").GetVariables()</code></term>
    ///             <description>this should return a set containing "X1", "Y1", and "Z1".</description>
    ///         </item>
    ///         <item>
    ///             <term><code>new("x1+X1"   ).GetVariables()</code></term>
    ///             <description>this should return a set containing "X1".</description>
    ///         </item>
    ///     </list>
    /// </summary>
    /// <returns> the set of variables (string names) representing the variables referenced by the formula.</returns>
    public ISet<string> GetVariables()
    {
        var searcher = new ExpressionDependencySearcher(_expression);
        var dependencies = searcher.Dependencies;
        var humanReadableDependencies = new HashSet<string>();

        // For each dependency, convert to human-readable form and add to set. The ExpressionDependencySearcher
        // already ensures that there are no duplicates, but we need to return a set of strings rather than
        // CellReferenceExpressions.
        foreach (var dependency in dependencies)
        {
            humanReadableDependencies.Add(
                CellReferenceCanonicalizer.Canonicalize(dependency.ColumnIndex, dependency.RowIndex));
        }

        return humanReadableDependencies;
    }

    /// <summary>
    ///     <para>
    ///         Returns a string representation of a canonical form of the formula.
    ///     </para>
    ///     <para>
    ///         The string will contain no spaces.
    ///     </para>
    ///     <para>
    ///         If the string is passed to the Formula constructor, the new Formula f
    ///         will be such that this.ToString() == f.ToString().
    ///     </para>
    ///     <para>
    ///         All the variable and number tokens in the string will be normalized.
    ///         For numbers, this means that the original string token is converted to
    ///         a number using double.Parse or double.TryParse, then converted back to a
    ///         string using double.ToString.
    ///         For variables, this means all letters are uppercased.
    ///     </para>
    ///     <para>
    ///         For example:
    ///     </para>
    ///     <code>
    ///         new("x1 + Y1").ToString() should return "X1+Y1"
    ///         new("x1 + 5.0000").ToString() should return "X1+5".
    ///     </code>
    ///     <para>
    ///         This method should execute in O(1) time.
    ///     </para>
    /// </summary>
    /// <returns>
    ///   A canonical version (string) of the formula. All "equal" formulas
    ///   should have the same value here.
    /// </returns>
    public override string ToString()
    {
        var canonicalizer = new ExpressionCanonicalizer(_expression);
        return canonicalizer.CanonicalForm;
    }
}

/// <summary>
///     <para>
///         Used to report syntax errors in the argument to the <see cref="Formula"/> constructor.
///     </para>
/// </summary>
public class FormulaFormatException : Exception
{
    /// <summary>
    ///     <para>
    ///         Initializes a new instance of the <see cref="FormulaFormatException"/> class.
    ///     </para>
    ///     <para>
    ///         Constructs a FormulaFormatException containing the explanatory message.
    ///   </para>
    /// </summary>
    /// <param name="message">A developer defined message describing why the exception occured.</param>
    public FormulaFormatException(string message)
        : base(message)
    {
        // All this does is call the base constructor. No extra code needed.
    }
}